### list
GET http://localhost:8080/coffees
Accept: application/json


### select one
GET http://localhost:8080/coffees/45f91545-9f75-4f2b-a130-89cbcb57f679
Accept: application/json


### select one
GET http://localhost:8080/coffees/9999
Accept: application/json


### post
POST http://localhost:8080/coffees
Content-Type: application/json

{"id" : "9999", "name" : "오늘의커피"}


### PUT
PUT http://localhost:8080/coffees/9999
Content-Type: application/json

{"id" : "9999", "name" : "아이스 아메리카노"}


### delete
DELETE http://localhost:8080/coffees/9999
Accept: application/json

### actuator
GET http://localhost:8080/actuator


### actuator/health
GET http://localhost:8080/actuator/health

